Проксируем события в другие каналы
vitalets/chnl pull request #12
Opened 2019-09-25 16:11 UTC by Procot

2019-09-25 16:17 UTC, Procot commented
@vitalets И кстати что там с документацией? Надо что-то поправлять, чтобы здесь https://vitalets.github.io/chnl/ появился мой добавленный метод?

2019-09-27 07:41 UTC, stamoern requested changes

2019-09-27 07:41 UTC, stamoern commented on src/channel.js
> +    this._proxyChannels.push(channel);
`channel instanceof Channel`? 
And also `this._proxyChannels.includes(channel)`

2019-09-27 07:41 UTC, stamoern commented on src/channel.js
> +  addProxyChannel(channel) {
I also propose to add `removeProxyChannel`/`removeAllProxyChannels`?

2019-10-04 15:16 UTC, vitalets commented
Please, use English )

2019-10-04 15:19 UTC, vitalets requested changes

2019-10-04 15:19 UTC, vitalets commented on src/channel.js
> +  'onProxyChannelAdded',
All of these is not needed:
'onProxyChannelAdded',
'onProxyChannelRemoved',
'onFirstProxyChannelAdded',
'onLastProxyChannelRemoved'

Proxying is just adding special listener.
Please update pr.

2019-10-04 15:19 UTC, vitalets commented on src/channel.js
> +    this._proxyChannels = [];
Not needed.

2019-12-30 12:01 UTC, vitalets requested changes

2019-12-30 12:01 UTC, vitalets commented on test/channel.test.js
> +  channel.dispatch();
Let's pass some data to ensure that data also proxied.

2019-12-30 12:01 UTC, vitalets commented on src/channel.js
> +      throw new Error('Channel ' + this._name + ': proxyChannel doesn\'t instance of Channel');
```js
`Channel ${this._name}: proxyChannel doesn't instance of Channel`
```

2019-12-30 12:05 UTC, stamoern commented on src/channel.js
> +      throw new Error('Channel ' + this._name + ': proxyChannel doesn\'t instance of Channel');
`doesn't` -> `is not`

2020-04-30 18:10 UTC, procot commented
@vitalets @stamoern 
Please check this PR.
I added support a channel as listener. Now we can using:
```js
const channel1 = new Channel();
const channel2 = new Channel();
const channel3 = new Channel();

channel1.addListener(channel2);
channel1.addOnceListener(channel3);
channel1.hasListener(channel2);

new Channel.ReactSubscription(component, [
  { channel: channel1, listener: channel2 }
])
```

2020-05-01 06:28 UTC, vitalets requested changes

2020-05-01 06:28 UTC, vitalets commented on src/subscription-item.js
> +    if (!listener || (typeof listener !== 'function' && !(listener instanceof Channel))) {
lets add static `Channel.isValidListener()` to avoid repeating `typeof listener !== 'function' && !(listener instanceof Channel)`

2020-05-02 08:32 UTC, vitalets approved these changes
lgtm 👍

2020-05-06 16:27 UTC, stamoern approved these changes

2020-05-06 16:33 UTC, merged