dispatchAsync method
vitalets/chnl pull request #7
Opened 2016-09-26 09:30 UTC by withw

@vitalets

2016-09-29 12:57 UTC, vitalets requested changes

2016-09-29 12:57 UTC, vitalets commented on src/channel.js
> +    setTimeout(() => this.dispatch(...args), 0);
I suggest to run each listener in own setTimeout. The benefit is that if there is error on one listenres all other will be called anyway.

2016-09-29 14:10 UTC, withw commented on src/channel.js
> +    setTimeout(() => this.dispatch(...args), 0);
Ok. Done it. Also add dispatchAsync calls accumulation, when channel is muted

2016-09-30 09:45 UTC, vitalets commented on src/channel.js
> +    setTimeout(() => this.dispatch(...args), 0);
Cool! Thanks!

2016-09-30 09:45 UTC, vitalets approved these changes

2016-09-30 10:26 UTC, merged